version: 2
jobs:
  build:

    working_directory: ~/banking-service

    docker:
      - image: circleci/openjdk:11-jdk-stretch

    steps:
      - checkout
      - restore_cache:
          key: banking-service-{{ checksum "pom.xml" }}

      - run: mvn clean integration-test install
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-banking-service-{{ checksum "pom.xml" }}

      - store_test_results:
          path: target/surefire-reports

      - store_test_results:
          path: target/failsafe-reports

      - run:
          name: Uploading coverage reports
          command: bash <(curl -s https://codecov.io/bash)