version: 1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout

      - restore_cache:
          key: maven-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Downloading dependencies
          command: ./mvnw dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Building and testing
          command: ./mvnw verify

      - store_test_results:
          path: target/surefire-reports