CREATE TABLE "CUSTOMER"
(
    "ID" NOT NULL VARCHAR(36) PRIMARY KEY,
    "NAME" NOT NULL VARCHAR(50),
    "DATE_OF_BIRTH" NOT NULL DATE,
    "MONTHLY_INCOME" NOT NULL NUMERIC,
    "CUSTOMER_ID" NOT NULL VARCHAR(36),
    "TAX_ID" NOT NULL VARCHAR(36)
)