CREATE TABLE "LOAN_REQUEST"
(
    "REQUEST_NUMBER" NOT NULL VARCHAR(36) PRIMARY KEY,
    "LOAN_AMOUNT" NOT NULL NUMERIC,
    "NUMBER_OF_INSTALLMENTS" NOT NULL INTEGER,
    "FIRST_INSTALLMENT_DATE" NOT NULL DATE,
    "REGISTRATION_DATE" NOT NULL TIMESTAMP,
    "EVALUATION_RESULT" NOT NULL VARCHAR(10)
)