CREATE TABLE "LOAN_REQUEST"
(
    "LOAN_REQUEST_NUMBER" VARCHAR(36) NOT NULL PRIMARY KEY,
    "LOAN_AMOUNT" NUMERIC NOT NULL,
    "LOAN_NUMBER_OF_INSTALLMENTS" INTEGER NOT NULL,
    "LOAN_FIRST_INSTALLMENT_DATE" DATE NOT NULL,
    "LOAN_REGISTRATION_DATE" TIMESTAMP NOT NULL,
    "LOAN_EVALUATION_RESULT" VARCHAR(10) NOT NULL,
    "CUSTOMER_NAME" VARCHAR(50) NOT NULL,
    "CUSTOMER_DATE_OF_BIRTH" DATE NOT NULL,
    "CUSTOMER_MONTHLY_INCOME" NUMERIC NOT NULL
)